### ISSUE TITLE
Unable to set thresholds on datadog monitor

### ISSUE THREAD

**Issue by thomasspatzier** [pulumi/pulumi-datadog#77]
I've been trying to use the datadog provider in my pulumi python program to create a datadog monitor. When following the docs at https://www.pulumi.com/docs/reference/pkg/python/pulumi_datadog/ to create a monitor including `thresholds` like this

```python
        my_monitor = datadog.Monitor(name='my name',
                                      resource_name='my-resource-name',
                                      type='metric alert',
                                      query='my query ...',
                                      tags=[
                                          'foo:bar',
                                      ],
                                      message='blah',
                                      thresholds=datadog.MonitorThresholdsArgs(
                                          ok=0,
                                          warning=2,
                                          warning_recovery=1,
                                          critical=4,
                                          critical_recovery=3,
                                      ),
                                      notify_no_data=False,
                                      renotify_interval=60,
                                      notify_audit=False,
                                      timeout_h=60,
                                      include_tags=True,
                                      opts=ResourceOptions(parent=self))
```

I get this error:

```
error: Traceback (most recent call last):
      File "/usr/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/local/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/local/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 426, in do_register
        await rpc.resolve_outputs(res, resolver.serialized_props, resp.object, resolvers)
      File "/usr/local/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 502, in resolve_outputs
        translated_value = translate_output_properties(value, res.translate_output_property, types.get(key))
      File "/usr/local/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 466, in translate_output_properties
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got '<class 'pulumi_datadog.outputs.MonitorThresholds'>'
```

I'm using pulumi 2.8.2. Also tried 2.10.0 but got the same error.
I also tried providing a dict instead of using `MonitorThresholdsArgs` class, but get the same issue.

**Comment by justinvp** [comment]
Sorry for the trouble, @thomasspatzier. We're tracking this issue at https://github.com/pulumi/pulumi-terraform-bridge/issues/251

In the meantime, you can avoid the issue by downgrading your PyPi packages to `pulumi` 2.8.2 and `pulumi_datadog` 2.6.0. You should be able to continue using the latest Pulumi CLI version.

**Comment by thomasspatzier** [comment]
@justinvp thanks for the update. I'll watch the other issue.
